# Only log to file
handlers = java.util.logging.FileHandler

.level = ALL

############################################################
# FileHandler configuration
############################################################
java.util.logging.FileHandler.pattern = ./mas.log
java.util.logging.FileHandler.limit = 500000
java.util.logging.FileHandler.count = 1
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.level = INFO

############################################################
# Disable console/GUI logging
############################################################
java.util.logging.ConsoleHandler.level = OFF
jason.runtime.MASConsoleLogHandler.level = OFF

############################################################
# Silence other verbose loggers
############################################################
java.level = OFF
javax.level = OFF
sun.level = OFF
jade.level = OFF
